---
  title: "viz_part_21"
author: "Troy Zhou"
output: github_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Let's import data

```{r}
library(tidyverse)
library(ggridges)
library(patchwork)
```

import weather dataset

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

better scatterplot

```{r}
weather_df %>% 
  ggplot(aes(x=tmin,y=tmax,color=name))+
  geom_point(alpha=.5)+
  labs(
    x="Minimum Daily Temp (C)",
    y="Maximum Dail Temp (C)",
    title="Scatterplot of daily temp extremes",
    caption="Data come from the rnoaa package"
  )+
  scale_x_continuous(
    breaks=c(-10,0,15),
    labels=c("-10C","0C","15C")
  )+
  scale_y_continuous(
    trans="sqrt"#square root transformation of y 
  )


```

make new version
change color scales using viridis 

```{r}
weather_df %>% 
  ggplot(aes(x=tmin,y=tmax,color=name))+
  geom_point(alpha=.5)+
  labs(
    x="Minimum Daily Temp (C)",
    y="Maximum Dail Temp (C)",
    title="Scatterplot of daily temp extremes",
    caption="Data come from the rnoaa package"
  )+
  scale_color_hue(
    name="Location",
    h=c(50,600)
  )

ggp_weather=
  weather_df %>% 
  ggplot(aes(x=tmin,y=tmax,color=name))+
  geom_point(alpha=.5)+
  labs(
    x="Minimum Daily Temp (C)",
    y="Maximum Dail Temp (C)",
    title="Scatterplot of daily temp extremes",
    caption="Data come from the rnoaa package"
  )+
  viridis::scale_color_viridis(#better than hue
    name="Location",
    discrete=TRUE
  )
```

put legend to bottom

```{r}
ggp_weather+
  theme(legend.position="bottom")

ggp_weather+
  theme_bw()

ggp_weather+
  theme_classic()

ggp_weather+
  theme_minimal()+
    theme(legend.position="bottom")
```

## data in geom()

```{r}
central_park_df=
  weather_df %>% 
  filter(name=="CentralPark_NY")

waikiki_df=
  weather_df %>% 
  filter(name=="Waikiki_HA")

ggplot(waikiki_df,aes(x=date,y=tmax))+
  geom_point()+
  geom_line(data=central_park_df)
```

## patchwork

```{r}
tmax_tmin_plot=
  weather_df %>% 
  ggplot(aes(x=tmin,y=tmax,color=name))+
  geom_point()

prcp_density_plot=
  weather_df %>% 
  filter(prcp>0) %>% 
  ggplot(aes(x=prcp,fill=name))+
  geom_density(alpha=.5)+
  theme(legend.position = "bottom")

seasonality_plot=
  weather_df %>% 
  ggplot(aes(x=date,y=tmax,color=name))+
  geom_point(alpha=.5)+
  theme(legend.position="bottom")

#patchwork
(tmax_tmin_plot+
prcp_density_plot)/seasonality_plot
```


## data manipulation

```{r}
weather_df %>% 
  mutate(name=fct_relevel(name,"Waikiki_HA")) %>% #MOVING TO FRONT
  ggplot(aes(x=name,y=tmax))+
  geom_boxplot()


weather_df %>% 
  mutate(name=fct_reorder(name,tmax)) %>% #reorder by tmax
  ggplot(aes(x=name,y=tmax))+
  geom_boxplot()
```

```{r}
pulse_df =
  haven::read_sas("data/public_pulse_data.sas7bdat") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    bdi_score_bl:bdiscore
  )
```

